New service k5login_generic
- new service k5login_generic (gen, send, slave)
- new attribute module k5loginTargetUser for k5login_generic service
- new method log_msg_without_exit

---------NEED TO BE DONE AFTER MERGE--------------
1] create new attribute resource_def_k5loginTargetUser
2] add rights for attribute k5loginTargetUser
3] create service k5loginTargetUser
4] add required attributes to this service

diff --git a/perun-services/slave/perun b/perun-services/slave/perun
--- a/perun-services/slave/perun
+++ b/perun-services/slave/perun
@@ -61,6 +61,24 @@ function log_msg {
 	fi
 }
 
+function log_msg_without_exit {
+	CODE=`eval echo '${'$1'[0]}'`
+  TEXT=`eval echo '${'$1'[1]}'`
+  TEXT=`eval echo \"${TEXT}\"`  # expand variables in message
+  CODE=${CODE:=255}
+  TEXT=${TEXT:=Unknown error $1}
+
+  if [ "${CODE}" -eq 0 ]; then
+    MSG="Info: ${TEXT}"
+    echo "${MSG}"
+    logger -t "${NAME}" -p daemon.info "${SERVICE}: ${MSG}" &>/dev/null
+  else
+    MSG="Error $1 (code=${CODE}): ${TEXT}"
+    echo "${MSG}" >&2
+    logger -t "${NAME}" -p daemon.error "${SERVICE}: ${MSG}" &>/dev/null
+  fi
+}
+
 ### Log debug only if variable DEBUG exists and is the length of this variable is nonzero
 function log_debug {
 	MSG="$1"
